"""Add access_info and booking_links to units

Revision ID: 6dd3c0ebcacc
Revises: c32fcf42fb3b
Create Date: 2026-01-20 16:19:02.350462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd3c0ebcacc'
down_revision: Union[str, None] = 'c32fcf42fb3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.
    
    Safety Guidelines:
    - New columns should be nullable or have server_default
    - Avoid dropping columns with existing data
    - For column type changes, use gradual migration (new column -> copy data -> drop old)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('booking_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.
    
    Note: Downgrades may not always be possible or safe.
    Test thoroughly before using in production.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('booking_links')
        batch_op.drop_column('access_info')

    # ### end Alembic commands ###
